name: nb-headless-content-blocks
type: typo3
docroot: .Build/public
php_version: "8.2"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "11.4"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "24"
corepack_enable: false
