name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install dependencies
        run: composer update --prefer-dist --prefer-stable --no-progress
      - name: Unit Tests
        run: Build/Scripts/runTests.sh -s unit -p 8.2

  functional_tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install dependencies
        run: composer update --prefer-dist --prefer-stable --no-progress
      - name: Functional Tests
        run: Build/Scripts/runTests.sh -s functional -d sqlite -p 8.2
